FROM node:12

WORKDIR /opt/

# React frontend
RUN git clone https://github.com/gothinkster/react-redux-realworld-example-app.git && \
    cd react-redux-realworld-example-app && \
    sed -i 's|https://conduit.productionready.io/api|/api|' src/agent.js && \
    npm install && \
    npm run build

# Simple webserver with configured proxy
FROM caddy

COPY --from=0 /opt/react-redux-realworld-example-app/build /usr/share/caddy

COPY ./Caddyfile /etc/caddy/Caddyfile
